### ISSUE TITLE
Can this model run on other platforms?

### ISSUE THREAD

**Issue by xbdxwyh** [Yang-YiFan/DiracDeltaNet#1]
Excuse me, I would like to ask, can this model run on other platforms (our platform is a zynq 7020 board)? After installing pytorch, is it feasible to follow the readme.md file steps(with the help of  your pre-trained model and organization of the project you provided) and run test.py directly？

**Comment by Yang-YiFan** [comment]
I'm afraid that it needs some extra steps to run the network on zync 7020. Ultra96 has a tiny os, i.e. pynq, which helps to directly run jupyter notebook on it. To my understanding, zynq7020 doesn't have such python interpreter. 
I can imagine running the network on zync 7020 needs:
1. writing a main program in c++ to do the control on the host cpu side
2. port the pretrained model from pytorch compatible format to a format which is recognized by your c++ program.
Thanks!
