### ISSUE TITLE
Qusetion about hardware

### ISSUE THREAD

**Issue by zxb-caffe** [Yang-YiFan/DiracDeltaNet#2]
Hello:
Can you provide hardware code?

**Comment by Yang-YiFan** [comment]
Sorry, we currently don't have the plan to release the hardware code. [This hardware code](https://github.com/KitAway/shiftNet) targets to run the [shiftresnet](https://github.com/alvinwan/shiftresnet-cifar) on Amazon F1 cloud FPGA, which shares a similar structure and architecture as our design. This could be a good reference to look at.
Thanks!
