### ISSUE TITLE
model of DiracDeltaNet_w1a4

### ISSUE THREAD

**Issue by Cathy-Cool** [Yang-YiFan/DiracDeltaNet#3]
Hello! Is it convenient for you to update the pretrained model of weights 1-bit and activations 4-bit model in the update paper? Thank you.

**Comment by Yang-YiFan** [comment]
Hi,
Sorry about the confusion. The quantization claim in the FPGA19 paper is inaccurate. We've updated the claim in the [arxiv version](https://arxiv.org/abs/1811.08634) and this repo. The quantization result we have is w4a4.
Thanks,
Yifan

**Comment by Cathy-Cool** [comment]
OK, I see. Thank you so much.
